#!/usr/bin/env python2
# -*- coding: utf-8 -*-

#***************************************************************************
#*   nepoogle - a Nepomuk's search engine inspired in Google search syntax *
#*                                                                         *
#*   Copyright                                                             *
#*   (C) 2011,12 Ignacio Serantes <kde@aynoa.net>                          *
#*                                                                         *
#*   This program is free software; you can redistribute it and/or modify  *
#*   it under the terms of the GNU General Public License as published by  *
#*   the Free Software Foundation; either version 2 of the License, or     *
#*   (at your option) any later version.                                   *
#*                                                                         *
#*   This program is distributed in the hope that it will be useful,       *
#*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
#*   GNU General Public License for more details.                          *
#*                                                                         *
#*   You should have received a copy of the GNU General Public License     *
#*   along with this program; if not, write to the                         *
#*   Free Software Foundation, Inc.,                                       *
#*   51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.         *
#***************************************************************************

import datetime, gettext, md5, os, re, signal, subprocess, sys, time

from PyQt4.QtCore import *
from PyKDE4.kdecore import *
from PyKDE4.nepomuk import *
from PyKDE4.soprano import *

from PyQt4.QtGui import *
from PyQt4.QtWebKit import *
from PyKDE4.kdeui import *
#from PyKDE4.kdecore import ki18n, i18n, KCmdLineArgs, KAboutData
#from PyKDE4.kdeui import KApplication, KXmlGuiWindow, KStandardAction, KAction, KIcon
#from PyKDE4.kdecore import *

#_BUG: carácter ' de Singin' in the Rain
#_BUG: fallan las búsquedas con el carácter ":"
#_BUG: encoding incorrecto
#_BUG: sample rate se visualiza en notación científica
#_BUG: error: [Errno 5] Input/output error la llamar al programa sin la consola
#_BUG: uri incorrecta en el link al album de la pieza musical
#_BUG: if file is unplugged and contains character "]" file is not displayed properly
#_TODO: visualizar las fechas correctamente
#_TODO: los links a visor deben funcionar con los discos desconectados
#_BUG: Modifiers "+" and "-" were not working filtering commands.
#_BUG: Duplicate entries, one for rdf:type of resourcer, when self.caseInsensitiveSort = True
#_TODO: sort case insensitive, columna lower(?x) AS ?sort
#_TODO: añadir totales y tiempos en consola
#_TODO: añadir al resource viewer los siguientes links: . << < > >>
#_TODO: extraer tipo y label de la propia db. Esto está actualmente hardcoded y
#_TODO: musicpiece debe de incluir el intérprete
#_TODO: añadir más información al contacto en la vista de resultados
#_TODO: implementar cache al moverse de atrás adelante (ojo con la vista por partes)

#BUG: BUG001 -> negation without a shorcut is failing.
#TODO: better history management.
#TODO: bif:lower(?x) in ('x', 'y', 'z')
#TODO: añadir soporte a nepomuk:/ en consola
#TODO: visor de álbum debería incluir los intérpretes/creadores del mismo y la carátula
#TODO: mostrar estrellas en el rating por coherencia
#TODO: count()
#select count(?x0) as ?cuantos
#where {
#{
#query a contar
#}
#}
#TODO: configuración externa
#TODO: multilenguage
#TODO: paréntesis
#TODO: editor: gestionar comentarios, rating y tags.
#TODO: soporte para la modificación de comentarios
#TODO: soporte para la modificación del rating
#TODO: soporte para la gestión de tags. Idea:
#       Más usados: los 10 tags más usados listados alfabéticamente.
#       Usados: los últimos tags usados, debajo los últimos que has usado.
#       Alfabética: la vista normal.
#       Botón de eliminar todos.
#TODO: añadir soporte a --connect, --disconnect, --daemonize y moverlos a Nepoogle
#TODO: todo en html para que pueda ser un servidor.

#IF BUILD
#INCLUDE lglobals.py
#ELSE
from lglobals import *
#ENDIF

_ = gettext.gettext

#IF BUILD
#INCLUDE lfunctions.py
#ELSE
from lfunctions import *
#ENDIF

#IF BUILD
#INCLUDE clsparql.py
#ELSE
from clsparql import *
#ENDIF

#IF BUILD
#INCLUDE cldataformat.py
#ELSE
from cldataformat import *
#ENDIF

#class nCompleter(QCompleter):

    #separator = " "

    #def __init__(self, *args):

        #super(nCompleter, self).__init__(*args)

        #model = QStringListModel()
        #wordList = [ \
                    #u"and", u"or",\
                    #u"actor:", \
                    #u"album", \
                    #u"creator", \
                    #u"director:", \
                    #u"genre", \
                    #u"hasTag:", \
                    #u"name:", \
                    #u"performer", \
                    #u"preflabel:", \
                    #u"rating:", \
                    #u"tag:", \
                    #u"title:", \
                    #u"url:", \
                    #u"writer:", \
                    #u"--help", \
                    #u"--allActors", \
                    #u"--allAlbums", \
                    ##u"--allCreators", \
                    #u"--allDirectors", \
                    #u"--allGenres", \
                    #u"--allPerformers", \
                    #u"--allTags", \
                    #u"--allWriters" \
                    #]

        #model.setStringList(wordList)
        #self.setModel(model)
        #self.setCaseSensitivity(Qt.CaseInsensitive);
        #self.setModelSorting(QCompleter.CaseSensitivelySortedModel)

        ##self.setCompletionMode(QCompleter.PopupCompletion)
        ##self.setCompletionMode(QCompleter.InlineCompletion)


    #def pathFromIndex(self, index):
        #path = QCompleter.pathFromIndex(self, index)

        #lst = str(self.widget().text()).split(self.separator)
        #if len(lst) > 1:
            #path = '%s%s%s' % (self.separator.join(lst[:-1]), self.separator, path)

        #return path


    #def splitPath(self, path):
        #path = str(path.split(self.separator)[-1]).lstrip(self.separator)
        #return [path]


#
# cWebView class
#
class cWebView(QWebView):

    owner = None

    def __init__(self, *args):
        super(cWebView, self).__init__(*args)

        #self.setContextMenuPolicy(Qt.PreventContextMenu)
        #self.setContextMenuPolicy(Qt.CustomContextMenu)
        self.owner = args[0]
        self.page().setLinkDelegationPolicy(QWebPage.DelegateAllLinks)
        self.page().setForwardUnsupportedContent(True)


    #def acceptNavigationRequest(frame, request, navigationType):
        #print("acceptNavigationRequest", frame, request, navigationType)


    #def createWindow(self, type):
        #print("createWindow", type)


    #def customContextMenuRequested(self, pos):
    #    print('customContextMenuRequested')


    #def contextMenuEvent(self, event):
    #    if False:
    #        self.popMenu = QMenu(self)
    #        self.popMenu.addAction("Open in New Window", self, SLOT(self.openLinkInNewWindow))
    #        self.popMenu.addSeparator()

    #    else:
    #        super(cWebView, self).contextMenuEvent(event)


    #def dragEnterEvent(self, event):
    #    print "dragEnterEvent", event.dropAction(), event.proposedAction(), event.spontaneous()
    #    event.setAccepted(True)

        #if (event.mimeData().hasFormat("text/plain")):
            #event.setDropAction(Qt.CopyAction)
            #event.accept()
            #print "Accepted: %s" % event.isAccepted()
            #event.acceptProposedAction();
            #print "Accepted: %s" % event.isAccepted()

        #self.dragOver = True;
        #self.update();


    def dragMoveEvent(self, event):
        if (event.mimeData().hasFormat("text/plain")):
            event.setAccepted(True)


    def dropEvent(self, event):
        self.owner.dropHandler(event)


    #def openLinkInNewWindow(self, url):
    #    print(url)


    #def triggerPageAction(action, checked):
    #    print(checked, action)

#
# Nepoogle class
#
class Nepoogle(QWidget):
    cache = []
    cacheViewer = []
    currUri = None
    clearResourceManagerCache = True
    keyModifiers = Qt.NoModifier
    model = None
    navigationData = []
    pendingQuery = False
    queriesIndex = -1
    queryMethod = None
    renderedCache = ''
    renderedRows = 0
    renderSize = 50
    resultData = []
    resultStructure = []
    resultTime = None
    sparql = None
    textToFind = ""
    verboseMode = False
    warningsList = []

    iconDelete = KIconLoader().iconPath('edit-delete', KIconLoader.NoGroup)
    iconDocumentInfo = KIconLoader().iconPath('documentinfo', KIconLoader.NoGroup)
    iconDocumentProp = KIconLoader().iconPath('document-properties', KIconLoader.NoGroup)
    iconFileManager = KIconLoader().iconPath('system-file-manager', KIconLoader.NoGroup)
    iconKonqueror = KIconLoader().iconPath('konqueror', KIconLoader.NoGroup)
    iconNavigateFirst = KIconLoader().iconPath('go-first', KIconLoader.NoGroup)
    iconNavigateLast = KIconLoader().iconPath('go-last', KIconLoader.NoGroup)
    iconNavigateNext = KIconLoader().iconPath('go-next', KIconLoader.NoGroup)
    iconNavigatePrevious = KIconLoader().iconPath('go-previous', KIconLoader.NoGroup)
    iconProcessIdle = KIconLoader().iconPath('process-idle', KIconLoader.NoGroup)
    iconSystemRun = KIconLoader().iconPath('system-run', KIconLoader.NoGroup)
    iconSystemSearch = KIconLoader().iconPath('system-search', KIconLoader.NoGroup)

    #htmlFooter = "%s</body>\n</html>\n" % PROGRAM_HTML_POWERED
    #htmlHeader = "<html>\n" \
                    #"<head>\n" \
                    #"<style type=\"text/css\">" \
                    #"    body {%(body_style)s}\n" \
                    #"    tr {%(tr_style)s}\n" \
                    #"    p {%(p_style)s}\n" \
                    #"</style>\n" \
                    #% {'body_style': "font-size:small;", \
                        #'p_style': "font-size:small;", \
                        #'tr_style': "font-size:small;" \
                        #} \
                    #+ "<title>%(title)s</title>\n" \
                        #"    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n" \
                        #"%(script)s\n" \
                        #"</head>\n<body>\n"
    #htmlImgStyle = "align=\"bottom\" border=\"0\" hspace=\"0\" vspace=\"0\" style=\"width: 14px; height: 14px;\""
    #htmlNavigateStyle  = "align=\"center\" border=\"0\" hspace=\"0\" vspace=\"0\" style=\"width: 20px; height: 20px;\""
    htmlTableHeader = "<table style=\"text-align:left; width: 100%%;\" " \
                        "border=\"%(border)s\" cellpadding=\"%(cellpadding)s\" cellspacing=\"0\">" \
                        "<tbody>\n"
    htmlTableFooter = "</tbody></table>\n"
    #htmlTime = "<br />\n%(records)s records found in %(seconds).4f seconds. \
                #HTML visualization builded in %(sechtml).4f seconds."


    #htmlLinkDolphin = "<a href=\"dolp:/%s\"><img %s title=\"%s\" src=\"file://%s\"></a>" \
                        #% ('%s', htmlImgStyle, 'open with Dolphin', iconFileManager)
    #htmlLinkInfo = "<img %s src=\"file://%s\">" % (htmlImgStyle, iconDocumentInfo)
    #htmlLinkKonqueror = "<a href=\"konq:/%s\"><img %s title=\"%s\" src=\"file://%s\"></a>" \
                        #% ('%s', htmlImgStyle, 'open with Konqueror', iconKonqueror)
    #htmlLinkNavigateFirst = "<a \"Go %(to)s\" href=\"navigate:/%(to)s\"><img %(style)s title=\"Go %(to)s\" src=\"file://%(icon)s\"></a>" \
                            #% {"to": "first", "style": htmlNavigateStyle, "icon": iconNavigateFirst}
    #htmlLinkNavigateLast = "<a \"Go %(to)s\" href=\"navigate:/%(to)s\"><img %(style)s title=\"Go %(to)s\" src=\"file://%(icon)s\"></a>" \
                            #% {"to": "last", "style": htmlNavigateStyle, "icon": iconNavigateLast}
    #htmlLinkNavigatePrevious = "<a \"Go %(to)s\" href=\"navigate:/%(to)s\"><img %(style)s title=\"Go %(to)s\" src=\"file://%(icon)s\"></a>" \
                            #% {"to": "previous", "style": htmlNavigateStyle, "icon": iconNavigatePrevious}
    #htmlLinkNavigateNext = "<a \"Go %(to)s\" href=\"navigate:/%(to)s\"><img %(style)s title=\"Go %(to)s\" src=\"file://%(icon)s\"></a>" \
                            #% {"to": "next", "style": htmlNavigateStyle, "icon": iconNavigateNext}
    #htmlLinkOpenLocation = "<a href=\"%s\"><img %s title=\"%s\" src=\"file://%s\"></a>" \
                            #% ('%s', htmlImgStyle, 'open location', iconFileManager)
    #htmlLinkProperties = "<a href=\"prop:/%s\"><img %s title=\"%s\" src=\"file://%s\"></a>" \
                            #% ('%s', htmlImgStyle, 'properties', iconDocumentInfo)
    #htmlLinkRemove = "<a href=\"remove:/%s\"><img %s title=\"%s\" src=\"file://%s\"></a>" \
                            #% ('%s', htmlImgStyle, 'remove resource', iconDelete)
    #htmlLinks = "<td width=\"65px\">%s</td>"
    #htmlLinkSearch = "<img %s src=\"file://%s\">" % (htmlImgStyle, iconSystemSearch)
    #htmlLinkSystemRun = "<a href=\"%s\"><img %s title=\"%s\" src=\"file://%s\"></a>" \
                            #% ('%s', htmlImgStyle, 'system run', iconSystemRun)


    def __init__(self, parent = None, searchString = '', verboseMode = False):
        super(Nepoogle, self).__init__(parent)

        self.verboseMode = verboseMode

        if DO_NOT_USE_NEPOMUK:
            self.model = Soprano.Client.DBusModel('org.kde.NepomukStorage', '/org/soprano/Server/models/main')

        else:
            self.model = Nepomuk.ResourceManager.instance().mainModel()

        #self.setGeometry(300, 300, 250, 150)
        #self.setWindowTitle(os.path.basename(sys.argv[0]))
        self.setWindowTitle(PROGRAM_NAME)
        #self.setWindowIcon(QIcon('icon.png'))
        self.setWindowIcon(QIcon(KIconLoader().loadIcon('nepomuk',  KIconLoader.NoGroup,  KIconLoader.SizeSmall)))

        self.leSearch = QLineEdit(self)
        #self.leSearch.setCompleter(nCompleter())
        self.leSearch.selectOnEntry = True

        self.pbBackward = QPushButton(self)
        self.pbBackward.setIcon(QIcon(KIconLoader().loadIcon('go-previous',  KIconLoader.NoGroup,  KIconLoader.SizeSmall)))
        #self.pbBackward.setGeometry(QRect(self.leSearch.height(), self.leSearch.height(), self.leSearch.height(), self.leSearch.height()))
        self.connect(self.pbBackward, SIGNAL("clicked()"), self.goBackward)

        self.pbForward = QPushButton(self)
        self.pbForward.setIcon(QIcon(KIconLoader().loadIcon('go-next',  KIconLoader.NoGroup,  KIconLoader.SizeSmall)))
        #self.pbForward.setGeometry(QRect(self.leSearch.height(), self.leSearch.height(), self.leSearch.height(), self.leSearch.height()))
        self.connect(self.pbForward, SIGNAL("clicked()"), self.goForward)

        self.pbHelp = QPushButton(self)
        self.pbHelp.setIcon(QIcon(KIconLoader().loadIcon('help-contents',  KIconLoader.NoGroup,  KIconLoader.SizeSmall)))
        #self.pbForward.setGeometry(QRect(self.leSearch.height(), self.leSearch.height(), self.leSearch.height(), self.leSearch.height()))
        self.connect(self.pbHelp, SIGNAL("clicked()"), self.showHelp)

        self.hbl = QHBoxLayout()
        self.hbl.setSpacing(1)
        self.hbl.addWidget(self.pbBackward)
        self.hbl.addWidget(self.pbForward)
        self.hbl.addWidget(self.leSearch)
        self.hbl.addWidget(self.pbHelp)

        self.wvOutput = cWebView(self)
        self.connect(self.wvOutput, SIGNAL("linkClicked(const QUrl&)"), self.linkClicked)
        self.connect(self.wvOutput, SIGNAL("loadStarted()"), self.loadStarted)
        self.connect(self.wvOutput, SIGNAL("loadFinished(bool)"), self.loadFinished)
        self.connect(self.wvOutput, SIGNAL("loadProgress(int)"), self.loadProgress)
        #self.connect(self.wvOutput, SIGNAL("dropEvent(QDropEvent*)"), self.dropHandler)
        #self.connect(self.wvOutput.page(), SIGNAL("customContextMenuRequested(const QPoint&)"), self.customContextMenuRequested)

        # This action has no changes.
        self.actionOpenLink = self.wvOutput.pageAction(QWebPage.OpenLink)
        self.connect(self.actionOpenLink, SIGNAL("triggered(bool)"), self.openLink)

        # DownloadLinkToDisk renamed and used as OpenLinkInNewWindow
        self.actionDownloadLinkToDisk = self.wvOutput.pageAction(QWebPage.DownloadLinkToDisk)
        self.actionDownloadLinkToDisk.setText(_("Open in New Window"))
        #self.connect(self.actionDownloadLinkToDisk, SIGNAL("triggered(bool)"), self.downloadLinkToDisk)

        # Invisible OpenLinkInNewWindow.
        self.actionOpenLinkInNewWindow = self.wvOutput.pageAction(QWebPage.OpenLinkInNewWindow)
        self.actionOpenLinkInNewWindow.setVisible(False)
        #self.connect(self.actionOpenLinkInNewWindow, SIGNAL("triggered(bool)"), self.openLinkInNewWindow)

        # Invisible OpenImageInNewWindow.
        self.actionOpenImageInNewWindow = self.wvOutput.pageAction(QWebPage.OpenImageInNewWindow)
        self.actionOpenImageInNewWindow.setVisible(False)

        self.connect(self.wvOutput.page(), SIGNAL("downloadRequested(const QNetworkRequest&)"), self.downloadRequested)
        self.connect(self.wvOutput.page(), SIGNAL("unsupportedContent(QNetworkReply*)"), self.unsupportedContent)
        self.wvOutput.page().setForwardUnsupportedContent(True)

        self.grid = QGridLayout()
        self.grid.setSpacing(10)
        #self.grid.addWidget(self.leSearch, 1, 1)
        self.grid.addLayout(self.hbl, 1, 1)
        self.grid.addWidget(self.wvOutput, 2, 1, 5, 1)

        self.setLayout(self.grid)

        self.resize(700, 600)
        if searchString == '':
            self.leSearch.setText(toUnicode('Type search here'))

        else:
            self.leSearch.setText(searchString)

        self.leSearch.setSelection(0,999)
        self.leSearch.setFocus()

        if searchString == '':
            self.execQuery('--help')


    #def downloadLinkToDisk(self, checked):
    #    print("downloadLinkToDisk", checked)
    #    pass


    def downloadRequested(self, request):
        #print("downloadRequested", request.url().toString())
        url = toUnicode(request.url().toString())
        if url != "":
            if url[:9] == 'nepomuk:/':
                pass

            elif url[:7] == 'query:/':
                url = url[7:]

            elif url[:6] == "file:/":
                subprocess.Popen(["kioclient", "exec", url])
                url = ''

            else:
                url = ''

            if url != '':
                print(toUtf8(url))
                subprocess.Popen([PROGRAM_URL, "--gui", toUtf8(url)])


    def unsupportedContent(self, request):
        #print("downloadRequested", request.url().toString())
        QMessageBox.warning(self, '%s - %s' % (PROGRAM_NAME, _("warning")), "Option not available yet.")


    def openLink(self, checked):
        #print("openLink", checked, toUtf8(self.wvOutput.page().currentFrame().requestedUrl()))
        url = toUnicode(self.wvOutput.page().currentFrame().requestedUrl())
        if url.toString() != "":
            self.linkClicked(url, True)


    def openLinkInNewWindow(self, checked):
        #print("openLinkInNewWindow", checked, toUtf8(self.wvOutput.page().currentFrame().requestedUrl()))
        url = toUnicode(self.wvOutput.page().currentFrame().requestedUrl().toString())
        if url != "":
            print(toUtf8(url))
            if url[:9] == 'nepomuk:/':
                pass

            elif url[:7] == 'query:/':
                url = url[7:]

            elif url[:6] == "file:/":
                subprocess.Popen(["kioclient", "exec", url])
                url = ''

            else:
                url = ''

            if url != '':
                subprocess.Popen([PROGRAM_URL, "--gui", toUtf8(url)])


    def loadFinished(self, ok):
        #print('loadFinished:', ok)
        self.repaint()
        if self.pendingQuery:
            self.execQuery()

        self.textToFind = ""

    def loadProgress(self, progress):
        #print('loadProgress:', progress)
        pass


    def loadStarted(self):
        #print('loadStarted', self.wvOutput.url().toString())
        pass


    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Return or event.key() == Qt.Key_Enter:
            self.pendingQuery = True
            self.queryMethod = "manual"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)

        elif event.key() == Qt.Key_F5:
            self.pendingQuery = True
            self.queryMethod = "refresh"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)

        elif event.key() == Qt.Key_F3:
            self.findText(True)

        elif event.modifiers() == Qt.ControlModifier:
            if event.key() == Qt.Key_PageUp:
                self.linkClicked(QUrl("navigate:/first"))

            elif event.key() == Qt.Key_PageDown:
                self.linkClicked(QUrl("navigate:/last"))

            elif event.key() == Qt.Key_Left:
                self.linkClicked(QUrl("navigate:/previous"))

            elif event.key() == Qt.Key_Right:
                self.linkClicked(QUrl("navigate:/next"))

            elif event.key() == Qt.Key_Delete:
                uri = toUnicode(self.leSearch.text()).strip()
                if uri[:13] == 'nepomuk:/res/':
                    self.linkClicked(QUrl("remove:/" + uri))

            elif event.key() == Qt.Key_F:
                self.findText()

            elif event.key() == Qt.Key_Plus:
                self.addProperty()

            #else
                #pass

        elif event.key() == Qt.Key_Escape:
            self.close()

        #elif event.key() == QKeySequence("Ctrl+E"):
        #    self.leSearch.keyPressEvent(self, event)

        #else
            #pass

        self.keyModifiers = event.modifiers()


    def keyReleaseEvent(self, event):
        self.keyModifiers = event.modifiers()


    def findText(self, again = False):
        if (not again or (self.textToFind == "")):
            self.textToFind = dialogInputBox(_("Text to find:"))

        self.wvOutput.findText("", QWebPage.HighlightAllOccurrences)
        if self.wvOutput.findText(self.textToFind, QWebPage.FindWrapsAroundDocument):
            self.wvOutput.findText(self.textToFind, QWebPage.HighlightAllOccurrences)


    def linkClicked(self, url, forceExec = False):
        url = toUnicode(url.toString())
        print(toUtf8(url))

        if url[:8] == 'delete:/':
            reply = QMessageBox.question(self, '%s - delete item' % PROGRAM_NAME, "Do you really want to send to trash this item??\n\n%s" % url[8:], QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
            if reply == QMessageBox.Yes:
                subprocess.Popen(['kioclient', 'move', url[8:], 'trash:/'])
                self.pendingQuery = True
                self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                                        % self.iconProcessIdle)
                if forceExec:
                    self.execQuery()
                    self.pendingQuery = False

        elif url[:6] == 'dolp:/':
            subprocess.Popen(['dolphin', url[6:]])

        elif url[:14] == 'googlesearch:/':
            url = "http://www.google.com:/search?q=%s&ie=UTF-8&oe=UTF-8" % url[14:].replace("?", "%3F")
            subprocess.Popen(["kioclient", "exec", url])

        elif url[:6] == 'konq:/':
            subprocess.Popen(['konqueror', url[6:]])

        elif url[:10] == 'navigate:/':
            if ((self.navigationData == []) or (len(self.navigationData) < 2)):
                return True

            idx = lindex(self.navigationData, self.leSearch.text(), 0)
            if idx != None:
                navigateTo = url[10:].lower()
                if navigateTo == "first":
                    idx = 0

                elif navigateTo == "previous":
                    if idx > 0:
                        idx -= 1

                elif navigateTo == "next":
                    if idx < len(self.navigationData) - 1:
                        idx += 1

                elif navigateTo == "last":
                    idx = len(self.navigationData) - 1

                #else:
                    #pass

                self.linkClicked(QUrl(self.navigationData[idx][0]), False)

        elif url[:9] == 'nepomuk:/':
            self.leSearch.setText(url)
            self.pendingQuery = True
            self.wvOutput.setHtml('<html><body><h3>Reading... <img src="file://%s"></h3></body></html>' \
                                    % self.iconProcessIdle)
            if forceExec:
                self.execQuery()
                self.pendingQuery = False

        elif url[:6] == 'prop:/':
            subprocess.Popen(['kioclient', 'openProperties', url[6:]])

        elif url[:9] == "propadd:/":
            uri = url[9:]
            self.addProperty(uri)

        elif url[:10] == "propedit:/":
            uri = url[10:].split("&")
            if (len(uri) == 2):
                if self.keyModifiers == Qt.NoModifier:
                    self.addProperty(uri[0], uri[1])

                elif self.keyModifiers == Qt.ShiftModifier:
                    self.editProperty(uri[0], uri[1])

                elif self.keyModifiers == Qt.ControlModifier:
                    self.removeProperty(uri[0], uri[1])

        elif url[:7] == 'query:/':
            urlElements = url[7:].split("'")
            if len(urlElements) >= 3:
                tmpUrl = urlElements[0] + '"'
                for i in range(1, len(urlElements) - 2):
                    tmpUrl += urlElements[i] + "'"
                tmpUrl += urlElements[-2] + '"'

            elif len(urlElements) == 2:
                tmpUrl = urlElements[0] + "'" + urlElements[1] + "'"

            elif len(urlElements) == 1:
                tmpUrl = "'" + urlElements[0] + "'"

            else:
                pass

            self.leSearch.setText(tmpUrl)
            self.pendingQuery = True
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                                    % self.iconProcessIdle)
            if forceExec:
                self.execQuery()
                self.pendingQuery = False

        elif url[:9] == "reindex:/":
            subprocess.Popen(["nepomukindexer", url[9:].replace("?", "%3F")])

        elif url[:8] == 'remove:/':
            reply = QMessageBox.question(self, '%s - remove resource' % PROGRAM_NAME, "Really delete this resource?", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
            if reply == QMessageBox.Yes:
                resource = Nepomuk.Resource(url[8:])
                resource.remove()
                self.pendingQuery = True
                self.queryMethod = "refresh"
                self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                                        % self.iconProcessIdle)
                if forceExec:
                    self.execQuery()
                    self.pendingQuery = False

        #elif url[:8] == 'render:/':
            #if url[8:] == 'more':
                #renderSize = 0

            #elif url[8:] == 'all':
                #if len(self.resultData) - self.renderedRows > self.renderSize * 3:
                    #reply = QMessageBox.question(self, '%s - render all' % PROGRAM_NAME, "This could be very slow. Continue?", QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                    #if reply != QMessageBox.Yes:
                        #return

                #renderSize = len(self.resultData)

            #else:
                #renderSize = -1

            #self.leSearch.readOnly = True
            #self.wvOutput.setHtml('<html><body><h3>Rendering... <img src="file://%s"></h3></body></html>' \
                                    #% self.iconProcessIdle)
            #self.wvOutput.repaint()
            #self.setCursor(Qt.BusyCursor)
            #self.repaint()
            #if renderSize >= 0:
                #self.wvOutput.setHtml(self.formatResultData([], [], [], 0, renderSize))

            #self.setCursor(Qt.ArrowCursor)
            #self.leSearch.readOnly = False
            #self.repaint()

        elif url[:8] == 'render:/':
            self.leSearch.readOnly = True
            self.wvOutput.setHtml('<html><body><h3>Rendering... <img src="file://%s"></h3></body></html>' \
                                    % self.iconProcessIdle)
            self.wvOutput.repaint()
            self.setCursor(Qt.BusyCursor)
            self.repaint()
            self.wvOutput.setHtml(self.cache[self.queriesIndex].formatAsHtml(url[8:]))

            self.setCursor(Qt.ArrowCursor)
            self.leSearch.readOnly = False
            self.repaint()

        elif url[:5] == 'run:/':
            if url[:12] == 'run:/file://':
                subprocess.Popen(["kioclient", "exec", url[12:]])

            else:
                subprocess.Popen(["kioclient", "exec", url[5:]])

        #elif url[:6] == 'view:/':
            #self.leSearch.setText(url[6:])
            #self.pendingQuery = True
            #self.wvOutput.setHtml('<html><body><h3>Reading... <img src="file://%s"></h3></body></html>' \
                                    #% self.iconProcessIdle)

        elif url[:11] == "setrating:/":
            rating = url[11:]
            try:
                rating = int(rating)

            except:
                rating = 0

            self.setRating(None, rating)

        else:
            # In KDE we trust.nepomuk:/res/eee8837d-27ab-43ac-a34a-43d339102c1c
            # Seems like there is a problem with character ?.
            subprocess.Popen(["kioclient", "exec", url.replace("?", "%3F")])


        # Clear always modifiers because the next keypress could happen in other window.
        self.keyModifiers = Qt.NoModifier


    def setRating(self, uri = None, rating = None):
        if (uri == None):
            uri = toUnicode(self.leSearch.text()).strip()
            if not uri[:13] == "nepomuk:/res/":
                QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("You can only add properties in the Resource Viewer."))
                return False

        if vartype(uri) == "Resource":
            resource = uri

        else:
            if self.model == None:
                return False

            if INTERNAL_RESOURCE:
                resource = cResource(uri)

            else:
                resource = Nepomuk.Resource(uri)

        if vartype(rating) == "int":
            pass

        elif vartype(rating) in ("str", "unicode"):
            try:
                rating = int(rating)

            except:
                rating = 0

        elif vartype(rating) == "QString":
            try:
                rating = int(toUnicode(rating))

            except:
                rating = 0

        if ((rating == None) or (rating < 0)):
            resource.removeProperty(toVariant(QUrl(resource.ratingUri())))
            rating = None

        else:
            rating = max(min(rating, 10), 0)
            resource.setRating(rating)

        if (vartype(uri) != "Resource"):
            time.sleep(SLEEP_AFTER_UPDATE)
            self.pendingQuery = True
            self.queryMethod = "refresh"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)

        return rating


    def addProperty(self, uri = None, ontology = "", text = ""):
        if (uri == None):
            uri = toUnicode(self.leSearch.text()).strip()

        if not uri[:13] == "nepomuk:/res/":
            QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("You can only add properties in the Resource Viewer."))
            return False

        mustRefresh = SLEEP_NO_SLEEP

        if self.model == None:
            return False

        if INTERNAL_RESOURCE:
            resource = cResource(uri)

        else:
            resource = Nepomuk.Resource(uri)

        resourceMainType = NOCR(resource.type())
        if ontology == "":
            query = 'SELECT DISTINCT ?r\n' \
                    'WHERE {\n' \
                        '\t{\n' \
                        '\t\t?r rdfs:domain %s .\n' \
                        '\t} UNION {\n' \
                        '\t\t?r rdfs:range rdfs:Literal .\n' \
                        '\t} UNION {\n' \
                        '\t\t?r rdfs:range xsd:string .\n' \
                        '\t}\n' \
                    '}\n' \
                    % (resourceMainType)

            values = []
            values += ["nao:numericRating"]
            queryResultSet = self.model.executeQuery(query, Soprano.Query.QueryLanguageSparql)
            if queryResultSet.isValid():
                while queryResultSet.next():
                    values += [NOCR(toUnicode(queryResultSet["r"].toString()))]

            if values != []:
                parameters = []
                status = "on"
                values.sort()
                for value in values:
                    parameters += [value, value, status]
                    if status == "on":
                        status = "off"

                ontologyResource, labelResource = dialogList(parameters, _("Select an ontology:"))
                if ((ontologyResource == None) or (ontologyResource == "")):
                    return False

        else:
            ontologyResource = ontology
            labelResource = ontology

        if not ((ontologyResource == None) or (ontologyResource == "")):
            if text == "":
                text = dialogInputBox(_("Value to store in \"%s\":") % ontologyResource)

            if text != "":
                #resourceReply = QMessageBox.question(self, '%s - add value' % PROGRAM_NAME, "Add \"%s\" as \"%s\"?" % (text, ontologyResource), QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                #if resourceReply == QMessageBox.Yes:
                if True:
                    print("%s: property %s added" % (uri, ontologyResource))
                    #print("Adding property: %s, %s, %s" % (uri, ontologyResource, text))
                    if ontologyResource == "nao:numericRating":
                        self.setRating(resource, text)

                    else:
                        resource.addProperty(QUrl(NOC(ontologyResource, True)), toVariant(text))

                    mustRefresh = SLEEP_AFTER_UPDATE

        else:
            QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("Sorry, I don't know what to do with this resource and custom ontologies are not supported yet."))

        if mustRefresh > SLEEP_NO_SLEEP:
            time.sleep(mustRefresh)
            self.pendingQuery = True
            self.queryMethod = "refresh"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)


    def editProperty(self, uri = None, ontology = None):
        if (uri == None):
            uri = toUnicode(self.leSearch.text()).strip()

        if not uri[:13] == "nepomuk:/res/":
            QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("You can only add properties in the Resource Viewer."))
            return False

        mustRefresh = SLEEP_NO_SLEEP

        if self.model == None:
            return False

        if INTERNAL_RESOURCE:
            resource = cResource(uri)

        else:
            resource = Nepomuk.Resource(uri)

        try:
            text = resource.property(NOC(ontology))
            if text.isStringList():
                QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("Only properties with one value could be edited."))
                return False

            text = toUnicode(resource.property(NOC(ontology)).toString())
            if text[:13] == "nepomuk:/res/":
                QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("You can't edit resources here, click in the resource and edit directly."))
                return False

        except:
            text = None

        if text != None:
            newText = dialogTextInputBox("Editing \"%s\":" % ontology, text)
            if newText != text:
                resourceReply = QMessageBox.question(self, '%s - edit value' % PROGRAM_NAME, _("Save changes to '%s'?") % (ontology), QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                if resourceReply == QMessageBox.Yes:
                    print("%s: property %s edited" % (uri, ontology))
                    if ontology == "nao:numericRating":
                        self.setRating(resource, newText)

                    else:
                        ontologyFull = QUrl(NOC(ontology, True))
                        if ontology in ("nie:url"):
                            resource.setProperty(ontologyFull, toVariant(newText))

                        else:
                            resource.removeProperty(ontologyFull, toVariant(text))
                            resource.addProperty(ontologyFull, toVariant(newText))

                    mustRefresh = SLEEP_AFTER_UPDATE

        if mustRefresh > SLEEP_NO_SLEEP:
            time.sleep(mustRefresh)
            self.pendingQuery = True
            self.queryMethod = "refresh"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)


    def removeProperty(self, uri = None, ontology = None):
        if ((uri == None) or (ontology == None)):
            return False

        mustRefresh = SLEEP_NO_SLEEP

        query = 'SELECT DISTINCT ?v\n' \
                'WHERE {\n' \
                    '\t<%s> %s ?v .\n' \
                '}\n' \
                % (uri, ontology)

        values  = []
        queryResultSet = self.model.executeQuery(query, Soprano.Query.QueryLanguageSparql)
        if queryResultSet.isValid():
            while queryResultSet.next():
                values += [NOCR(toUnicode(queryResultSet["v"].toString()))]

        if values != []:
            resourcesList = []
            for value in values:
                if value[:13] == "nepomuk:/res/":
                    if INTERNAL_RESOURCE:
                        label = cResource(value).genericLabel()

                    else:
                        label = toUnicode(Nepomuk.Resource(value).genericLabel())

                else:
                    label = value

                resourcesList += [[value, label]]

            if (len(values) > 1):
                resourcesList = sorted(resourcesList, key=lambda item: item[1])
                # Convert to 1 dimension.
                parameters = []
                status = "on"
                for param in resourcesList:
                    parameters += [param[0]] + [param[1]] + [status]
                    if status == "on":
                        status = "off"

                value, label = dialogList(parameters, _("Select the value to be removed:"))

            else:
                value = resourcesList[0][0]
                label = resourcesList[0][1]

            if ((value != None) and (value != "")):
                reply = QMessageBox.question(self, '%s - remove property' % PROGRAM_NAME, "Remove property \"%s\" with value \"%s\"?" % (ontology, label), QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                if reply == QMessageBox.Yes:
                    print("%s: property %s removed" % (uri, ontology))
                    #print("Removing property: %s, %s, %s" % (uri, ontology, toUtf8(value)))
                    if (len(values) == 1):
                        resource = Nepomuk.Resource(uri)
                        resource.removeProperty(QUrl(NOC(ontology)))
                        mustRefresh = SLEEP_AFTER_UPDATE

                    else:
                        resource = Nepomuk.Resource(uri)
                        resource.removeProperty(QUrl(NOC(ontology)), toVariant(value))
                        mustRefresh = SLEEP_AFTER_UPDATE

        if mustRefresh > SLEEP_NO_SLEEP:
            time.sleep(mustRefresh)
            self.pendingQuery = True
            self.queryMethod = "refresh"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)


    def dropHandler(self, event):
        supportedImageFormats = QImageReader.supportedImageFormats() + ["nef"]
        mustRefresh = SLEEP_NO_SLEEP

        #Qt::KeyboardModifiers QDropEvent::keyboardModifiers () const
        #Qt::MouseButtons QDropEvent::mouseButtons () const
        #QWidget * QDropEvent::source () const para controlar el d&d sobre si mismo.

        # Query para obtener las propiedades "oficiales".
        # SELECT * WHERE { ?r rdfs:domain %s .}

        # Query para obtener qué puede ser un resource.
        #SELECT * WHERE { ?r rdfs:range %s . }

        uri = toUnicode(self.leSearch.text()).strip()
        if not uri[:13] == "nepomuk:/res/":
            QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("You can only drop data in the Resource Viewer."))
            return False

        if event.mimeData().hasUrls():
            imageReply = resourceReply = None
            for i in range(0, len(event.mimeData().urls())):
                url = toUnicode(event.mimeData().urls()[i].toString()).strip()
                print("url: %s" % toUtf8(url))

                dropType = None
                if dropType == None:
                    ext = os.path.splitext(url)[1][1:].lower()
                    if ((ext != '') and fileExists(url)):
                        if ext in supportedImageFormats:
                            dropType = "image"

                if dropType == None:
                    if url[:13] == "nepomuk:/res/":
                        dropType = "resource"

                if dropType == None:
                    if ((url[:7] == "http://") or (url[:8] == "https://")):
                        dropType = "url"

                if dropType == None:
                    if (url[:10] == "propedit:/"):
                        try:
                            ontValue = url[10:].split("&")[1]

                        except:
                            ontValue = ""

                        self.addProperty(uri, ontValue)
                        continue

                if dropType == None:
                    if (url[:9] == "propadd:/"):
                        self.addProperty(uri)
                        continue

                if dropType == "image":
                    if (i == 0):
                        parameters = [ONTOLOGY_SYMBOL, ONTOLOGY_SYMBOL, "off", ONTOLOGY_SYMBOL_CONTACT, ONTOLOGY_SYMBOL_CONTACT, "off", "nfo:depiction", "nfo:depiction", "on", "nmm:artwork", "nmm:artwork", "off"]
                        ontologyImages, labelImages = dialogList(parameters, _("Select an ontology:"))
                        if ((ontologyImages == None) or (ontologyImages == "")):
                            continue

                        if (len(event.mimeData().urls()) > 1):
                            msgImagePronoun = "all images"

                        else:
                            msgImagePronoun = "next image"

                        msgImageUrl = "\n\n" + "\n".join([toUnicode(urlItem.toString()) for urlItem in event.mimeData().urls()])
                        imageReply = QMessageBox.question(self, _("%s - add data") % PROGRAM_NAME, _("add %s as %s?%s") % (msgImagePronoun, ontologyImages, msgImageUrl), QMessageBox.Yes | QMessageBox.No, QMessageBox.No)

                    if imageReply == QMessageBox.Yes:
                        uriResource = Nepomuk.Resource(uri)
                        uriResource.addProperty(NOC(ontologyImages, True), toVariant(url))
                        mustRefresh = SLEEP_AFTER_UPDATE

                elif dropType == "url":
                    urlReply = QMessageBox.question(self, '%s - add resource' % PROGRAM_NAME, "Add \"%s\" as \"%s\"?" % (url, ONTOLOGY_LINK), QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                    if urlReply == QMessageBox.Yes:
                        urlResource = Nepomuk.Resource(url)
                        if url.find("://") > 0:
                            url = QUrl(url)

                        urlResource.setProperty(NOC("nie:url", True), toVariant(url))
                        uriResource = Nepomuk.Resource(uri)
                        uriResource.addProperty(NOC(ONTOLOGY_LINK, True), toVariant(urlResource.uri()))
                        mustRefresh = SLEEP_AFTER_UPDATE

                else:
                    if self.model == None:
                        return False

                    if INTERNAL_RESOURCE:
                        resource = cResource(url)

                    else:
                        resource = Nepomuk.Resource(url)

                    resourceMainType = NOCR(resource.type())
                    resourceGenericLabel = resource.genericLabel()

                    if dropType == "resource":
                        query = 'SELECT DISTINCT ?r\n' \
                                'WHERE {\n' \
                                    '\t?r rdfs:range %s .\n' \
                                '}\n' \
                                % (resourceMainType)

                    else:
                        query = 'SELECT DISTINCT ?r\n' \
                                'WHERE {\n' \
                                    '\t?r rdfs:domain %s .\n' \
                                '}\n' \
                                % (resourceMainType)

                    values = []
                    queryResultSet = self.model.executeQuery(query, Soprano.Query.QueryLanguageSparql)
                    if queryResultSet.isValid():
                        while queryResultSet.next():
                            values += [NOCR(toUnicode(queryResultSet["r"].toString()))]

                    if values != []:
                        parameters = []
                        status = "on"
                        values.sort()
                        for value in values:
                            parameters += [value, value, status]
                            if status == "on":
                                status = "off"

                        ontologyResource, labelResource = dialogList(parameters, _("Select an ontology:"))
                        if ((ontologyResource == None) or (ontologyResource == "")):
                            continue

                        resourceReply = QMessageBox.question(self, '%s - add resource' % PROGRAM_NAME, "Add \"%s\" as \"%s\"?" % (resourceGenericLabel, ontologyResource), QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
                        if resourceReply == QMessageBox.Yes:
                            print("%s: property %s added" % (uri, ontologyResource))
                            #print("Adding property: %s, %s, %s" % (uri, ontologyResource, url))
                            resourceResource = Nepomuk.Resource(uri)
                            resourceResource.addProperty(QUrl(NOC(ontologyResource, True)), toVariant(url))
                            mustRefresh = SLEEP_AFTER_UPDATE

                    else:
                        QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("error")), _("Sorry, I don't know what to do with this resource and custom ontologies are not supported yet."))

        elif event.mimeData().hasText():
            text = toUnicode(event.mimeData().text())
            if text == "":
                return False

            self.addProperty(uri, "", text)

        if mustRefresh > SLEEP_NO_SLEEP:
            time.sleep(mustRefresh)
            self.pendingQuery = True
            self.queryMethod = "refresh"
            self.wvOutput.setHtml('<html><body><h3>Searching... <img src="file://%s"></h3></body></html>' \
                % self.iconProcessIdle)


    def goBackward(self):
        #print("Go backward")
        refresh = False
        searchText = self.leSearch.text()
        #if not searchText[:3] in ("e0 ", "e2 "):
        #    searchText = "e1 " + searchText

        if self.queriesIndex >= 0 and searchText != self.cache[self.queriesIndex].searchString:
            refresh = True

        else:
            if (self.queriesIndex > 0):
                self.queriesIndex -= 1
                refresh = True

        if refresh:
            self.setCursor(Qt.BusyCursor)
            searchString = self.cache[self.queriesIndex].searchString
            #if searchString[:3] == "e1 ":
            #    searchString = searchString[3:]

            self.leSearch.setText(searchString)
            self.pendingQuery = False
            self.wvOutput.setHtml(self.cache[self.queriesIndex].formatAsHtml())
            self.setCursor(Qt.ArrowCursor)
            self.leSearch.readOnly = False
            self.repaint()
            self.navigationData = self.cache[self.queriesIndex].data


    def goForward(self):
        #print("Go forward")
        if (self.queriesIndex < (len(self.cache) - 1)):
            self.queriesIndex += 1
            self.setCursor(Qt.BusyCursor)
            searchString = self.cache[self.queriesIndex].searchString
            #if searchString[:3] == "e1 ":
            #    searchString = searchString[3:]

            self.leSearch.setText(searchString)
            self.pendingQuery = False
            self.wvOutput.setHtml(self.cache[self.queriesIndex].formatAsHtml())
            self.setCursor(Qt.ArrowCursor)
            self.leSearch.readOnly = False
            self.repaint()
            self.navigationData = self.cache[self.queriesIndex].data


    def showHelp(self):
        self.leSearch.setText("--help")
        self.pendingQuery = False
        self.wvOutput.setHtml(self.buildHelp(self.sparql))
        self.repaint()


    def buildHelp(self, oSparqlBuilder):
        commands = '<p><b>Commands</b>:\n<ul>\n'
        for command in oSparqlBuilder.commands:
            commands += '<li>%s</li>\n' % command[0]
        commands += '</ul></p>\n'

        shortcuts = '<p><b>Onlologies shorcuts</b>:<ul>\n' + self.htmlTableHeader \
                        % {'border': 0, 'cellpadding': 0}
        for shortcut in oSparqlBuilder.shortcuts:
            info = ''
            fmtOntology = shortcut[0]
            if fmtOntology.find('%') >= 0:
                fmtOntology = fmtOntology.replace('%', '')
                info += ' (using percent encoding)'

            elif fmtOntology.find('!') >= 0:
                fmtOntology = fmtOntology.replace('!', '')
                info += ' (supports duplicated properties)'

            if fmtOntology.find('_') >= 0:
                fmtOntology = fmtOntology.replace('_', '')
                info += ' (using optionals to negate)'

            shortcuts += '<tr><td><b>%(abr)s</b>, <b>%(shortcut)s</b>:</td><td><em>%(ontology)s</em>%(info)s</td></tr>\n' \
                                % {'abr': shortcut[2], 'shortcut': shortcut[1], 'ontology': fmtOntology, 'info': info}

        shortcuts += self.htmlTableFooter + '</ul></p>\n'

        remarks = "<p><b>Remarks</b>:<br \>\n" \
                    "<ul>\n" \
                    "<li>This program was tested on <b>KDE 4.8.1</b>." \
                    "<li>Nepomuk search api is available using e0 or e2 as prefix.</li>\n" \
                    "<li><b>Virtuoso 6.1.4</b> or greater is required to use Nepomuk search api.</li>\n" \
                    "<li>Query syntax is inspired in Google's search syntax.</li>\n" \
                    "<li>Nepoogle do a text search in identifiers, descriptions, tags, fullnames, titles and urls.</li>\n" \
                    "<li>Parenthesis for group queries are not supported.</li>\n" \
                    "<li>You can use regular expressions searching strings.</li>\n" \
                    "<li>Nepoogle's own engine works with Soprano and don't uses Nepomuk to do queries.</li>\n" \
                    "<li>Be cautious, certain ontologies combinations in a same query may offer 0 results.</li>\n" \
                    "</ul></p>\n" \

        commandsList = ''
        for command in oSparqlBuilder.commands:
            if commandsList != '':
                commandsList += ' | ' + command[0]

            else:
                commandsList += command[0]

        shortcutsList = ''
        for shortcut in oSparqlBuilder.shortcuts:
            if shortcutsList != '':
                shortcutsList += ' | ' + shortcut[1]

            else:
                shortcutsList += shortcut[1]

        syntax = "<p><b>The query syntax is</b>:<ul>\n" \
                    "<em>query</em> :== e0 querystring<sup>1)</sup><br />\n"\
                    "<em>query</em> :== e2 querystring<sup>2)</sup><br />\n"\
                    "<br />\n" \
                    "<em>query</em> :== [e1] item [[logop] item]... | command | uri<br />\n"\
                    "<br />\n" \
                    "<em>logop</em> :== and | or<br />\n" \
                    "<em>compop</em> :==  = | < | <= | > | >=<br />\n" \
                    "<em>op</em> :== + | - | compop<br />\n" \
                    "<br />\n" \
                    "<em>item</em> :== [ontology:][op]text | &lt;ontology&gt;&lt;op&gt;&lt;text&gt;<br />\n" \
                    "<br />\n" \
                    "<em>ontology</em> :== [ontitem=]ontitem[->[ontitem=]ontitem]]...<br />\n" \
                    "<em>ontitem</em> :== shortcutontology | shortontology | fullontology<br />\n" \
                    "<em>shortcutontology</em> :== %(shortcuts)s<br />\n" \
                    "<em>shortontology</em> :== prefix:name<br />\n" \
                    "<em>fullontology</em> :== &lt;http://fullurl&gt;<br />\n" \
                    "<br />\n" \
                    "<em>text</em> :== date | number | string | time<br />\n" \
                    "<em>date</em> :== yyyy-mm-dd | month | day | year<br />\n" \
                    "<em>month</em> :== 1..12[m]<br />\n" \
                    "<em>day</em> :== 13..31 | 1..31d<br />\n" \
                    "<em>year</em> :== 31..9999 | 1..9999y<br />\n" \
                    "<em>number</em> :== posnumber | negnumber | fraction<br />\n" \
                    "<em>posnumber</em> :== 0..9<br />\n" \
                    "<em>negnumber</em> :== compop-0..9<br />\n" \
                    "<em>fraction</em> :== posnumber/posnumber | negnumber/posnumber<br />\n" \
                    "<em>string</em> :== chars | \"chars\" | 'chars'<br />\n" \
                    "<em>chars</em> :== any number of utf-8 characters<br />\n" \
                    "<em>time</em> :== hh:mm:ss | hour | minute | seconds<br />\n" \
                    "<em>hour</em> :== 1..24[h]<br />\n" \
                    "<em>minute</em> :== 25..60 | 1..60m<br />\n" \
                    "<em>seconds</em> :== 1..60s<br />\n" \
                    "<br />\n" \
                    "<em>command</em> :== instruction[:string]<br />\n" \
                    "<em>instruction</em> :== %(instructions)s<br />\n" \
                    "<br />\n" \
                    "<sup>1)</sup>e0 uses <a href=\"http://api.kde.org/4.x-api/kdelibs-apidocs/nepomuk-core/html/classNepomuk_1_1Query_1_1QueryParser.html\">Nepomuk::Query::QueryParser()</a> and it has its own query syntax.<br />" \
                    "<sup>2)</sup>e2 uses a hacked version of <a href=\"http://api.kde.org/4.x-api/kdelibs-apidocs/nepomuk-core/html/classNepomuk_1_1Query_1_1QueryParser.html\">Nepomuk::Query::QueryParser()</a> optimized with subqueries.<br />" \
                    "</ul>" \
                    "</p>\n" \
                    % {'shortcuts': shortcutsList, 'instructions': commandsList}

        examples = "<p><b>Examples</b>:\n" \
                    + self.htmlTableHeader % {'border': 1, 'cellpadding': 2} + \
                    "<tr><td><b>query</b></td>\n" \
                        "<td><b>result</b></td></tr>\n" \
                    "<tr><td><em>movie</em></td>\n" \
                        "<td>contains word 'movie'</td></tr>\n" \
                    "<tr><td><em>+movie</em></td>\n" \
                        "<td>equals word 'movie'</td></tr>\n" \
                    "<tr><td><em>-movie</em></td>\n" \
                        "<td>not contains word 'movie'</td></tr>\n" \
                    "<tr><td><em>hastag:-dorama +'takeuchi yuuko' 'hiroshi'</em></td>\n" \
                        "<td>not tagged as 'dorama' and equals 'takeuchi yuuko' and contains 'hiroshi'</td></tr>\n" \
                    "<tr><td><em>movie or hasTag:'takeuchi yuuko'</em></td>\n" \
                        "<td>contains movie or tagged 'takeuchi yuuko'</td></tr>\n" \
                    "<tr><td><em>hasTag:+movie rating:>=5</em></td>\n" \
                        "<td>tagged exactly 'movie' and rating >= 5</td></tr>\n" \
                    "<tr><td><em>url:\"^file:///media\" mimetype:image mimetype:-image/jpeg</em></td>\n" \
                        "<td>all image files, except jpegs, located in /media</td></tr>\n" \
                    "<tr><td><em>mimetype:image/png height:>=1200 width:>=1600</em></td>\n" \
                        "<td>all pngs with a resolution great or equal to 1600x1200</td></tr>\n" \
                    "<tr><td><em>playcount:0 hastag:corea genre:drama actor:+'Yeong-ae Lee' director:Park</em></td>\n" \
                        "<td>not played movie dramas tagged 'corea' with actress 'Yeong-ae Lee' and with director name contains 'Park'</td></tr>\n" \
                    "<tr><td><em>actor:'Zhang Ziyi' and actor:-'Bingbing Fan'</em></td>\n" \
                        "<td>movies with actress 'Zhang Ziyi' but without actress 'Bingbing Fan'</td></tr>\n" \
                    "<tr><td><em>tvshow:Coupling season:2 episode:4</em></td>\n" \
                        "<td>Episode 4 of Season 2 of Coupling</td></tr>\n" \
                    "<tr><td><em>--tags</em></td>\n" \
                        "<td>all tags</td></tr>\n" \
                    "<tr><td><em>--actors:luppi</em></td>\n" \
                        "<td>all actors containing 'luppi'</td></tr>\n" \
                    + self.htmlTableFooter + \
                    "</p>\n"

        output = "<html>\n  <head>\n"\
                    "<style type=\"text/css\">" \
                    "body {%(body_style)s}\n" \
                    "p {%(p_style)s}\n" \
                    "ul {%(ul_style)s}\n" \
                    "li {%(li_style)s}\n" \
                    "tr {%(tr_style)s}\n" \
                    "</style>\n" \
                    "<title>%(title)s</title>\n    " \
                    "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">" \
                    "\n  </head>\n<body>\n" \
                    "<p><h3>%(program)s's help</h3></p>\n" \
                    "<p><b>%(program)s</b> is a system to query the <em>Nepomuk's database</em>. <b>%(program)s</b> does not search the file system so that only returns results that are pre-collected in <em>Nepomuk's database</em>.</p>\n" \
                    "%(examples)s" \
                    "%(remarks)s" \
                    "%(shortcuts)s" \
                    "%(commands)s" \
                    "%(syntax)s" \
                    "For bugs, suggestions or wishes send a mail to kde@aynoa.net\n" \
                    "%(powered)s</body>\n</html>" \
                    % {'title': 'Querying Nepomuk', \
                        'error': sys.exc_info()[1], \
                        'program': os.path.basename(sys.argv[0]), \
                        'powered': PROGRAM_HTML_POWERED, \
                        'remarks': remarks, \
                        'syntax': syntax, \
                        'shortcuts': shortcuts, \
                        'commands': commands, \
                        'examples': examples, \
                        'body_style': "font-size:small", \
                        'p_style': "font-size:small", \
                        'ul_style': "font-size:small", \
                        'li_style': "font-size:small", \
                        'tr_style': "font-size:small;" \
                        }

        return output


    def htmlRenderLink(self, id = 'uri', par1 = '', par2 = ''):
        if id == 'uri':
            title = "title=\"%s\"" % par1
            href = "href=\"%s\"" % par1
            value = par2

        elif id == 'album':
            title = "title=\"album:+\'%s\'\"" % par1
            href = "href=\"query:/album:+\'%s\'\"" % par1
            value = self.htmlLinkSearch

        elif id == 'contact':
            title = "title=\"contact:+\'%s\'\"" % par1
            href = "href=\"query:/contact:+\'%s\'\"" % par1
            value = self.htmlLinkSearch

        elif id == 'navigator':
            return "%s%s%s%s" % (self.htmlLinkNavigateFirst, \
                                    self.htmlLinkNavigatePrevious, \
                                    self.htmlLinkNavigateNext, \
                                    self.htmlLinkNavigateLast)

        elif id == 'ontology':
            title = "title=\"%s:+\'%s\'\"" % (par1, par2)
            href = "href=\"query:/%s:+\'%s\'\"" % (par1, par2)
            value = self.htmlLinkSearch

        elif id == 'performer':
            title = "title=\"performer:+\'%s\'\"" % par1
            href = "href=\"query:/performer:+\'%s\'\"" % par1
            value = self.htmlLinkSearch

        elif id == 'tag':
            title = "title=\"hasTag:+\'%s\'\"" % par1
            href = "href=\"query:/hasTag:+\'%s\'\"" % par1
            value = self.htmlLinkSearch

        # This is an exception.
        elif id == 'unplugged':
            if par1 == '':
                return "<b>[Unplugged<a title=\"uuid:%s\" href=\"prop:/%s\">%s</a>]</b><em>%s</em>" \
                        % (par2[8:].split('/')[0], \
                            par2[8:].split('/')[0], \
                            self.htmlLinkInfo, \
                            '/' + '/'.join(par2[8:].split('/')[1:]) \
                            )

            else:
                return "<b>[Unplugged<a title=\"uuid:%s\" href=\"prop:/%s\">%s</a>]</b><a title=\"%s\" href=\"%s\"><em>%s</em></a>" \
                        % (par2[8:].split('/')[0], \
                            par2[8:].split('/')[0], \
                            self.htmlLinkInfo, \
                            par1, \
                            par1, \
                            '/' + '/'.join(par2[8:].split('/')[1:]) \
                            )

        elif id == 'url':
            title = "title=\"%s\"" % par1
            href = "href=\"%s\"" % par1
            value = par2
            #TODO: añadir un icono que indique que es un enlace externo.

        else:
            return ''

        return "<a %s %s>%s</a>" % (title, href, value)


    def processMacros(self, searchString = ""):
        if searchString.find("--m0:") >= 0:
            searchString = searchString.replace("--m0:", "--playlist genre:-instrumental performer:")

        elif searchString.find("--m1:") >= 0:
            searchString = searchString.replace("--m1:", "--playlist genre:-instrumental nmm:musicAlbum->nmm:albumArtist->nco:fullname:")

        return searchString


    def execQuery(self, searchString = ''):
        self.leSearch.readOnly = True
        self.setCursor(Qt.BusyCursor)
        self.repaint()

        self.renderedRows = 0
        self.renderedCache = ''

        self.resultData = []
        self.resultStructure = []
        self.resultTime = None

        searchEngine = DEFAULT_ENGINE
        if searchString == '':
            searchString = toUnicode(self.leSearch.text().trimmed().toUtf8())

        #if True:
        try:
            if not DO_NOT_USE_NEPOMUK and self.clearResourceManagerCache:
                Nepomuk.ResourceManager.instance().clearCache()

            self.sparql = cSparqlBuilder()
            if searchString[:9] == 'nepomuk:/':
                self.currUri = searchString
                if self.queryMethod in ("manual", "refresh"):
                    cachedData = None

                else:
                    cachedData = lvalue(self.cacheViewer, searchString, 0, 1)

                if cachedData == None:
                    oDataFormat = cDataFormat(searchString, self.model)
                    #output = oDataFormat.formatResourceInfo(searchString, self.sparql.shortcuts, self.sparql.ontologyTypes)
                    output = oDataFormat.formatResourceInfo(searchString, self.sparql.shortcuts, ontologyTypes)

                else:
                    output = cachedData

                if self.queryMethod == "manual":
                    # Cache must be trunked in current position if query changed.
                    if ((self.queriesIndex >= 0) and (self.queriesIndex < len(self.cache))):
                        if self.cache[self.queriesIndex].searchString != searchString:
                            self.cache = self.cache[:self.queriesIndex + 1]

                    if (self.cache == []) or (self.cache[self.queriesIndex].searchString != searchString):
                        self.cache += [oDataFormat]
                        self.queriesIndex += 1

                    else:
                        self.cache[self.queriesIndex] = oDataFormat

                    self.navigationData = []

                if cachedData == None:
                    i = lindex(self.cacheViewer, searchString, 0)
                    if i == None:
                        self.cacheViewer += [[searchString, output.replace("<cached />", " (cached)")]]

                    else:
                        self.cacheViewer[i][1] = output.replace("<cached />", " (cached)")

            elif searchString != '':
                self.currUri = None
                searchString = self.processMacros(searchString)
                if searchString[:3].lower() in ('e0 ', 'e1 ', 'e2 '):
                    searchEngine = int(searchString[1:2])

                else:
                    searchEngine = DEFAULT_ENGINE
                    searchString = "e%d %s" % (searchEngine, searchString)

                externalParameters = []
                if searchEngine == 0:
                    oNQP = Nepomuk.Query.QueryParser()
                    processedSearchString = searchString[3:]
                    for command in ["--playlist", "--playmixed"]:
                        if processedSearchString.find(command) >= 0:
                            externalParameters += [command]
                            processedSearchString = processedSearchString.replace(command, "")

                    query = toUnicode(oNQP.parse(processedSearchString).toSparqlQuery())
                    oNQP = None
                    if (self.verboseMode and sys.stdout.isatty()):
                        # Improve a little bit readability.
                        print(toUtf8(query.replace(" where ", " WHERE ").replace("{", "{\n").replace("}", "\n}").replace("} .", "} .\n").replace("} UNION {", " } UNION {").replace(". ?", ".\n ?").replace("\n ?", "\n  ?").replace("\n} .", "\n } .").replace("} .\n  ?", "} .\n ?")))

                    query = hackQueryParser(query, 'e0')
                    self.resultData, self.resultStructure, self.resultTime = self.sparql.executeQuery(query)

                elif searchEngine == 2:
                    oNQP = Nepomuk.Query.QueryParser()
                    processedSearchString = searchString[3:]
                    for command in ["--playlist", "--playmixed"]:
                        if processedSearchString.find(command) >= 0:
                            externalParameters += [command]
                            processedSearchString = processedSearchString.replace(command, "")

                    query = toUnicode(oNQP.parse(processedSearchString).toSparqlQuery())
                    oNQP = None
                    query = hackQueryParser(query, 'e2')
                    if (self.verboseMode and sys.stdout.isatty()):
                        # Improve a little bit readability.
                        print(toUtf8(query.replace(" where ", " WHERE ").replace("{", "{\n").replace("}", "\n}").replace("} .", "} .\n").replace("} UNION {", " } UNION {").replace(". ?", ".\n ?").replace("\n ?", "\n  ?").replace("\n} .", "\n } .").replace("} .\n  ?", "} .\n ?")))

                    self.resultData, self.resultStructure, self.resultTime = self.sparql.executeQuery(query)

                else:
                    searchString = searchString[3:]
                    self.sparql.stdoutQuery = (self.verboseMode and sys.stdout.isatty())
                    self.sparql.columns = '?x0 AS ?id ' + self.sparql.columns
                    self.resultData, self.resultStructure, self.resultTime = self.sparql.executeQuery(self.sparql.buildQuery(searchString))
                    self.warningsList = self.sparql.warningsList
                    self.sparql.warningsList = []

                oDataFormat = cDataFormat(searchString, self.model)
                if ((self.sparql.externalParameters == ['playlist']) or (externalParameters == ['--playlist'])):
                    output = oDataFormat.formatAsHtmlPlaylist('playlist', self.resultData, self.resultStructure, self.resultTime)

                elif ((self.sparql.externalParameters == ['playlist']) or (externalParameters == ['--playmixed'])):
                    output = oDataFormat.formatAsHtmlPlaylist('playmixed', self.resultData, self.resultStructure, self.resultTime)

                else:
                    output = oDataFormat.formatAsHtml(self.resultData, self.resultStructure, self.resultTime)

                # Cache must be trunked in current position if query changed.
                if ((self.queriesIndex >= 0) and (self.queriesIndex + 1 < len(self.cache))):
                    if self.cache[self.queriesIndex].searchString != searchString:
                        self.cache = self.cache[:self.queriesIndex + 1]

                if (self.cache == []) or (self.cache[self.queriesIndex].searchString != searchString):
                    self.cache += [oDataFormat]
                    self.queriesIndex += 1

                else:
                    self.cache[self.queriesIndex] = oDataFormat

                self.navigationData = self.cache[self.queriesIndex].data

            else:
                raise Exception('Please, type something.')

        #try:
        #    pass

        except:
            msgError = "%s" % sys.exc_info()[1]
            if msgError == 'help':
                output = self.buildHelp(self.sparql)

            elif msgError == 'quit':
                quit()

            else:
                output = "<html>\n  <head>\n    <title>%(title)s</title>\n    " \
                            "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">" \
                            "\n  </head>\n<body><b>error:</b> %(error)s" \
                            "%(powered)s</body>\n</html>" \
                            % {'title': 'Querying Nepomuk', \
                                'error': sys.exc_info()[1], \
                                'powered': PROGRAM_HTML_POWERED \
                                }

        self.pendingQuery = False
        self.queryMethod = None
        self.wvOutput.setHtml(output)
        self.setCursor(Qt.ArrowCursor)
        self.leSearch.readOnly = False
        self.repaint()

        # Handle possible warnings.
        warningMsg = ""
        for warning in self.warningsList:
            if warningMsg != "":
                warningMsg += "\n\n"

            if warning[0] == "BUG001":
                warningMsg += "There is a know bug using negation without a shortcut.\n" \
                        "Please notice that the results may be inaccurate.\n\n"
                for i in range(1, len(warning)):
                    warningMsg += "Change \"%s\" for something like \"title:%s\" to solve this issue.\n" \
                    % (warning[i], warning[i])

            #else:
                #pass

        self.warningsList = []

        if warningMsg != "":
            QMessageBox.warning(self, "%s - %s" % (PROGRAM_NAME, _("warning")), warningMsg)


def hackQueryParser(query = '', hackLevel = 'e2'):

    if query.find("?v7 ") == -1:
        # Don't change queries with only one item.
        return query

    if hackLevel.lower() == 'e2':
        query = query.replace(' ?r <http://www.semanticdesktop.org/ontologies/2007/08/15/nao#userVisible> ?v1 . FILTER(?v1>0) .', '')
        query = query.replace(' UNION { ?r ', ' UNION { ?0 ')
        query = query.replace(' { ?r ', ' { SELECT ?r WHERE { { ?r <http://www.semanticdesktop.org/ontologies/2007/08/15/nao#userVisible> 1 . ?r ')
        query = query.replace(' UNION { ?0 ', ' UNION { ?r ')
        query = query.replace(' } .', '}}} .')
        query = query.replace('.}}} .}}} . }', '. }}} . }')

        # Removing ?_n_f_t_m_ex_ field to avoid duplicates in the result.
        query = "SELECT DISTINCT ?r " + query[query.find("where"):]
        query = query.replace('SELECT DISTINCT ?r where { { { ', 'SELECT DISTINCT ?r WHERE { { ')

    elif hackLevel.lower() == 'e0':
        # Removing ?_n_f_t_m_ex_ field to avoid duplicates in the result.
        query = "SELECT DISTINCT ?r " + query[query.find("where"):]

    return query


def buildHelp():
    print("%(name)s %(version)s (%(date)s)\n" \
              % {'name': PROGRAM_NAME, 'version': PROGRAM_VERSION_VERSION, 'date': PROGRAM_VERSION_DATE})

    print("Usage: %s [command ] [query]\n" \
          "\n" \
          "commands:\n" \
          "  --help           -- Shows this help\n" \
          "  --gui[=MODE]     -- Mode: ON, OFF, force gui mode (defaults ON)\n" \
          "  --results[=MODE] -- Mode: ON, OFF, displays results in console mode (defaults ON)\n" \
          "  --verbose[=MODE] -- Mode: ON, OFF (defaults ON with --gui parameter)\n" \
          "\n" \
          "query:\n" \
          "  Query syntax documentation is available in the gui mode help\n" \
          % PROGRAM_NAME)


def main(args):
    #appName = PROGRAM_NAME
    #catalog = PROGRAM_NAME
    #programName = ki18n(PROGRAM_NAME)
    #version = PROGRAM_VERSION_VERSION
    #description = ki18n("An alternate search engine for Nepomuk inspired in Google search syntax.")
    #license = KAboutData.License_GPL
    #copyright = ki18n("(C) 2011 Ignacio Serantes")
    #text = ki18n("A search engine for Nepomuk.")
    #homePage = "http://kde-apps.org/content/show.php/Nepoogle?content=145505"
    #bugEmail = "kde@aynoa.net"

    #aboutData = KAboutData(appName, catalog, programName, version,
                            #description, license, copyright, text, homePage,
                            #bugEmail)

    #KCmdLineArgs.init(sys.argv, aboutData)

    #options = KCmdLineOptions()
    #options.add("--help", ki18n("this help"))
    #options.add("--gui", ki18n("force gui mode in console"))
    #options.add("--stdout", ki18n("force stdout in console mode"))
    #options.add("--nostdout", ki18n("force no stdout in gui mode"))
    #KCmdLineArgs.addCmdLineOptions(options)

    displayResults = None
    gui = not sys.stdout.isatty()
    verboseMode = None
    parameters = toUnicode('')
    paramOption = ""
    for i in range(1, len(args)):
        parameter = toUnicode(args[i].strip())

        if parameter.lower() == '--help':
            buildHelp()
            quit()

        elif parameter.lower()[:5] == '--gui':
            paramValue = parameter.lower()[5:]
            if paramValue == "" or paramValue == "=on":
                gui = True

            elif paramValue == "=off":
                gui = False

            else:
                print("ERROR: Unknown parameter \"%s\".\n" % parameter)
                buildHelp()
                quit()

            continue

        elif parameter.lower()[:9] == '--verbose':
            paramValue = parameter.lower()[9:]
            if paramValue == '':
                if verboseMode == None:
                    verboseMode = True

            elif paramValue == '=on':
                verboseMode = True

            elif paramValue == '=off':
                verboseMode = False

            else:
                print("ERROR: Unknown parameter \"%s\".\n" % parameter)
                buildHelp()
                quit()

            continue

        elif parameter.lower()[:9] == '--results':
            paramValue = parameter.lower()[9:]
            if paramValue == '':
                if verboseMode == None:
                    displayResults = True

            elif paramValue == '=on':
                displayResults = True

            elif paramValue == '=off':
                displayResults = False

            else:
                print("ERROR: Unknown parameter \"%s\".\n" % parameter)
                buildHelp()
                quit()

            continue

        elif parameter.find(' ') >= 0:
            j = parameter.rfind(':')
            if j >= 0:
                parameter = parameter[:j+1] + '"' + parameter[j+1:] + '"'

            else:
                parameter = '"' + parameter + '"'

        parameters += parameter + ' '

    searchString = parameters.strip()
    if gui:
        if verboseMode == None:
            verboseMode = gui

        #app = KApplication()
        #window = Nepoogle(searchString)
        #window.show()

        #if searchString != '':
        #    window.execQuery()

        app = QApplication(args)
        nepoogle = Nepoogle(None, searchString, verboseMode)
        nepoogle.show()
        nepoogle.repaint()
        if searchString != '':
            nepoogle.execQuery()

        sys.exit(app.exec_())

    else:
        if verboseMode == None:
            verboseMode == False

        searchEngine = DEFAULT_ENGINE
        if searchString[:3].lower() in ('e0 ', 'e1 ', 'e2 '):
            searchEngine = int(searchString[1:2])

        output = "%(title)s\n" % {'title': 'Querying Nepomuk' }
        print(toUtf8(output))

        #if True:
        try:
            warningsList = []
            oSparql = cSparqlBuilder()
            if searchString != '':

                if searchEngine == 0:
                    oNQP = Nepomuk.Query.QueryParser()
                    query = toUnicode(oNQP.parse(searchString[3:]).toSparqlQuery())
                    oNQP = None
                    if verboseMode:
                        # Improve a little bit readability.
                        print(toUtf8(query.replace(" where ", "\nwhere ").replace("{", "{\n").replace("}", "\n}").replace("} .", "} .\n").replace("} UNION {", " } UNION {").replace(". ?", ".\n ?").replace("\n ?", "\n  ?").replace("\n} .", "\n } .").replace("} .\n  ?", "} .\n ?")))

                    query = hackQueryParser(query, 'e0')
                    data, structure, time = oSparql.executeQuery(query)

                elif searchEngine == 2:
                    oNQP = Nepomuk.Query.QueryParser()
                    query = toUnicode(oNQP.parse(searchString[3:]).toSparqlQuery())
                    oNQP = None
                    query = hackQueryParser(query, 'e2')
                    if verboseMode:
                        # Improve a little bit readability.
                        print(toUtf8(query.replace(" where ", "\nwhere ").replace("{", "{\n").replace("}", "\n}").replace("} .", "} .\n").replace("} UNION {", " } UNION {").replace(". ?", ".\n ?").replace("\n ?", "\n  ?").replace("\n} .", "\n } .").replace("} .\n  ?", "} .\n ?")))

                    data, structure, time = oSparql.executeQuery(query)

                else:
                    oSparql.stdoutQuery = verboseMode
                    oSparql.columns = '?x0 AS ?id ' + oSparql.columns
                    data, structure, time = oSparql.executeQuery(oSparql.buildQuery(searchString))
                    warningsList =  oSparql.warningsList
                    oSparql.warningsList = []

                oSparql = None

                if displayResults in (None, True):
                    oDataFormat = cDataFormat(searchString)
                    oDataFormat.formatAsText(data, structure, time)

                output = "\n%(records)s records found in %(seconds).4f seconds.\n" \
                            "--\n" \
                            "Powered by %(name)s %(version)s (%(date)s)" \
                            % {'records': len(data), \
                                'seconds': time, \
                                'name': PROGRAM_NAME, \
                                'version': PROGRAM_VERSION_VERSION, \
                                'date': PROGRAM_VERSION_DATE \
                                }

                # Handle possible warnings.
                warningMsg = ""
                for warning in warningsList:
                    if warningMsg != "":
                        warningMsg += "\n\n"

                    if warning[0] == "BUG001":
                        warningMsg += "There is a know bug using negation without a shortcut.\n" \
                                "Please notice that the results may be inaccurate.\n\n"
                        for i in range(1, len(warning)):
                            warningMsg += "Change \"%s\" for something like \"title:%s\" to solve this issue.\n" \
                            % (warning[i], warning[i])

                    #else:
                        #pass

                warningsList = []

                if warningMsg != "":
                    output += '\n\nWARNING: ' + toUtf8(warningMsg)

            else:
                raise Exception('Please, type something.')

        #try:
        #    pass

        except KeyboardInterrupt:
            output = "\nOperation aborted by user...\n" \
                        "\n--\n" \
                        "Powered by %(name)s %(version)s (%(date)s)" \
                        % {'title': 'Querying Nepomuk', \
                            'error': sys.exc_info()[1], \
                            'name': PROGRAM_NAME, \
                            'version': PROGRAM_VERSION_VERSION, \
                            'date': PROGRAM_VERSION_DATE \
                            }

        except:
            msgError = "%s" % sys.exc_info()[1]
            if msgError == 'help':
                output = buildHelp()

            else:
                output = "\nerror: %(error)s\n" \
                            "\n--\n" \
                            "Powered by %(name)s %(version)s (%(date)s)" \
                            % {'title': 'Querying Nepomuk', \
                                'error': sys.exc_info()[1], \
                                'name': PROGRAM_NAME, \
                                'version': PROGRAM_VERSION_VERSION, \
                                'date': PROGRAM_VERSION_DATE \
                                }

        print(toUtf8(output))


if __name__=="__main__":
    display = os.getenv("DISPLAY")
    if display == None:
        os.putenv("DISPLAY", ":0")

    main(sys.argv)
